### Instruction Manual:

#Best practice would be to create a conda environment with the required packages installed. (You might need to install python first)

Run in the terminal of your computer (type command prompt in you search bar to open the terminal) it might be needed to navigate to the directory where you run this ipynb file  first (cd ..)

#step 1:
conda create -n pystad-env python=3.13


#Step 2: activating your newly create conda environment
conda activate pystad-env

#Step 3 if you want to be able to activate this conda env in a jupyter notebook (make sure you open your jupyternotebook in the same directory as where you created your conda environment in the terminal)
conda install ipykernel

Press CTRL+ENTER in order to run each cell and move to the next cell.

##### Make sure you download the pystad package from the google drive folder I shared with you (https://drive.google.com/drive/u/0/folders/1bKhhpZafTQtW2J7JcHJvsWJTc03oDhnE) before proceeding.

In [1]:
#Adjust the path to the folder you downloaded so that it matches the file location on your machine. Download this package from the goolgle drive https://drive.google.com/drive/folders/1ZyEq-A5q0Rcfs5QyuR0ae6eT8dFt8Rl-?usp=drive_link
!pip install "C:/Users/P70095226/Documents/pySTAD-0.2.11"

Processing c:\users\p70095226\documents\pystad-0.2.11
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.20.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pySTAD==0.2.11) (1.26.4)
Requirement already satisfied: networkx>=3.0.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pySTAD==0.2.11) (3.5)
Requirement already satisfied: scipy>=1.6.3 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pySTAD==0.2.11) (1.16.2)
Requirement already satisfied: matplotlib>=3.4.2 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pySTAD==0.2.11) (3.10.7)
Requirement already satisfied: pandas>=1.1.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pySTAD==0.2.11) (2.3.3)
Requirement already satisfied: ipywidgets>=7.6.3 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pySTAD==0.2.11) (8.1.7)
Requirement already satisfied: pywin32>=1.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pySTAD==0.2.11) (311)
Requirement already satisfied: comm>=0.1.3 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipywidgets>=7.6.3->pySTAD==0.2.11) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipywidgets>=7.6.3->pySTAD==0.2.11) (9.5.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipywidgets>=7.6.3->pySTAD==0.2.11) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipywidgets>=7.6.3->pySTAD==0.2.11) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipywidgets>=7.6.3->pySTAD==0.2.11) (3.0.15)
Requirement already satisfied: colorama in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (0.4.6)
Requirement already satisfied: decorator in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (2.19.1)
Requirement already satisfied: stack_data in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (0.8.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from matplotlib>=3.4.2->pySTAD==0.2.11) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pandas>=1.1.0->pySTAD==0.2.11) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from pandas>=1.1.0->pySTAD==0.2.11) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.4.2->pySTAD==0.2.11) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets>=7.6.3->pySTAD==0.2.11) (0.2.3)
Building wheels for collected packages: pySTAD
  Building wheel for pySTAD (pyproject.toml): started
  Building wheel for pySTAD (pyproject.toml): finished with status 'done'
  Created wheel for pySTAD: filename=pystad-0.2.11-py3-none-any.whl size=4235860 sha256=1385abd0ea0dab464e753282ab88ab77d950b5517954a6883fe41403a9ed456c
  Stored in directory: c:\users\p70095226\appdata\local\pip\cache\wheels\e7\00\73\c605ceeecbddb03fd1ad1852b8a8fca366ce143b1e1361aefa
Successfully built pySTAD
Installing collected packages: pySTAD
  Attempting uninstall: pySTAD
    Found existing installation: pySTAD 0.2.11
    Uninstalling pySTAD-0.2.11:
      Successfully uninstalled pySTAD-0.2.11
Successfully installed pySTAD-0.2.11

In [2]:
# Run this cell to install the required packages. 
import sys
import subprocess

# List of all known pySTAD dependencies
packages = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "python-igraph",
    "panel",
    "vega",
    "pyArango",
    "networkx",
    "matplotlib"
]

# Install each package in the current kernel
for pkg in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", pkg])

print("All pySTAD dependencies should now be installed.")

All pySTAD dependencies should now be installed.

In [4]:
#run this because the newest numpy version might cause issues, restart your kernal after running this so that the udpated package is used. 
!pip install "numpy<2.0"
import json
import numpy as np
import pandas as pd
import stad as sd
from scipy.spatial.distance import pdist, squareform
import matplotlib.pyplot as plt
from pyArango.connection import *
import networkx as nx

Requirement already satisfied: numpy<2.0 in c:\users\p70095226\appdata\local\anaconda3\envs\pystad-env\lib\site-packages (1.26.4)

Falling back to slow stad.sparse implementation
Falling back to slow stad.sparse implementation
Falling back to slow stad.objective implementation
Falling back to slow stad.masks implementation
Falling back to slow stad.lenses implementation

In [5]:
# format of credentials.json file that should be in the directory in which you are running this script. (To connect to personal ArangoDB environemnt)
#     { "url": "http://localhost:8529",
#       "databaseName": "",
#       "auth": { "username": "", "password": "
#     }

credentials = json.load(open('credentials.json'))
print(credentials)

{'url': 'http://localhost:8529', 'databaseName': '_system', 'auth': {'username': 'root', 'password': 'openSesame'}}

In [7]:
#To check whether connection was succesfull, you need your arangodb Database open in the browser to verify the connection with this cell. 
conn = Connection(username=credentials["auth"]["username"], password=credentials["auth"]["password"])
db = conn[credentials["databaseName"]]
db

ArangoDB database: _system

In [9]:
## Do not change this but check whether it corresponds with the rows of your dataset. 
labels = [ "HC01", "HC02", "HC03", "HC04", "HC05", "HC06", "HC07", "HC08", "HC09", "HC10", "HC11", "HC12", "HC13", "HC14", "HC15", "HC16", "HC17", "HC18",
  "LC05", "LC06", "LC07", "LC08", "LC09", "LC10", "LC11", "LC12", "LC13", "LC14", "LC15", "LC01", "LC02", "LC03", "LC04",
  "ME13", "ME14", "ME01", "ME02", "ME03", "ME04", "ME05", "ME06", "ME07", "ME08", "ME09", "ME10", "ME11", "ME12"
]

In [ ]:
#Make sure you have the optimalBBS3004_nometa.csv file in the same directory as this notebook.
from scipy.spatial.distance import pdist, squareform
df = pd.read_csv('optimal_BBS3004_nometa.csv', sep=',', encoding='latin-1')
df.index = labels
df = df.iloc[:, 1:]
df

,CD96,ACSL4,DLD,GRB2,AKT3,GLS,ROCK1,PLCG2,IL27RA,OAS1,...,TOX,PTPN18,SESN3,MX2,CD14,GADD45A,GOT2,HLA-DPB1,PVRIG,IL1R2
HC01,10.982416,8.581878,9.808387,11.486202,10.640772,11.129492,10.645381,9.391978,9.527985,9.375427,...,8.375427,5.745377,9.745377,7.828793,10.989684,6.638462,7.812491,12.425192,10.131136,5.440522
HC02,11.074435,8.576681,9.812611,11.732433,11.019372,11.187450,10.806899,9.024303,9.229202,9.569340,...,7.833192,6.264485,10.455803,7.904943,11.077458,7.346947,7.608072,12.510497,9.759836,5.655069
HC03,10.914452,8.655718,9.822777,11.494021,10.918484,11.022040,10.715642,9.033238,9.429563,9.538361,...,8.249242,6.340216,10.240680,7.681253,11.152144,6.576283,7.548803,12.883506,9.903645,5.018288
HC04,10.783415,8.793556,9.946802,11.632977,10.690462,11.169195,10.790443,9.395007,9.297519,10.099225,...,8.349203,5.520537,10.216346,7.670285,11.215186,6.293127,7.968998,13.457421,9.653251,4.579431
HC05,9.935061,8.896855,9.703045,11.812413,9.739862,10.348112,10.419353,9.014212,9.465423,9.791193,...,7.129689,6.751177,9.339142,7.696036,12.324446,5.921102,7.760166,13.650081,9.804289,5.184137
HC06,11.112262,6.557673,10.172383,12.993343,11.332460,11.540666,11.008884,6.258113,10.676614,12.053528,...,5.879601,7.767126,9.686956,9.033406,11.671415,4.879601,5.365028,13.481743,10.352089,4.557673
HC07,10.448196,8.480638,9.878230,11.832426,10.631166,10.743816,10.121161,8.805337,9.556631,10.572988,...,7.613088,5.424054,9.503005,7.970022,11.668941,6.521665,7.791425,13.273553,9.528391,4.587553
HC08,11.359028,8.066246,9.817219,11.622780,11.050324,11.142488,10.382533,8.531424,9.397993,9.134959,...,8.275509,5.340962,10.382533,7.546637,9.490054,7.194121,8.016123,12.779620,9.835915,4.556691
HC09,10.383005,9.020246,9.892554,12.077646,10.185260,10.329217,10.271921,8.888840,9.096282,10.250377,...,7.428479,5.989367,9.594989,7.835822,12.552783,6.888840,7.780780,13.898798,9.488600,6.681245
HC10,11.187663,8.825317,10.104005,11.836326,11.146441,11.520491,11.086508,9.679551,9.232294,10.290218,...,7.703799,6.118836,10.721181,8.527301,10.787657,6.446001,8.170366,13.451544,9.599571,5.622879
HC11,11.641585,8.697062,10.416954,11.552624,11.304601,11.801571,11.583889,9.597790,9.022675,8.674752,...,8.046039,6.255963,11.097964,7.800283,11.144029,7.486917,7.295491,12.738434,10.154816,4.893392
HC12,10.482521,9.114267,10.338828,12.040766,10.618553,10.910734,10.969628,9.463275,8.829814,9.811198,...,8.159122,5.714337,10.572318,8.129374,11.372548,7.414777,7.533097,13.677072,9.607807,7.067974
HC13,10.806456,9.081533,10.205650,11.996075,10.409505,11.117127,10.942393,9.431531,9.204538,10.428201,...,7.564015,5.746218,9.998643,8.144346,11.813584,7.167356,7.743159,13.265455,9.418164,5.355428
HC14,10.488903,9.242884,10.152382,12.130997,10.369804,10.985638,11.120776,9.728311,9.185198,10.392202,...,7.838920,6.154696,10.203940,8.045883,11.749132,6.861760,7.689473,13.416188,9.241434,7.560456
HC15,11.062505,8.957875,10.031456,11.819323,10.567097,11.170046,10.883102,9.329272,9.078505,10.327650,...,8.109039,6.189822,10.540039,8.109039,11.054682,6.160967,7.858040,12.488713,9.612428,4.619073
HC16,11.113274,8.495994,9.763689,11.625677,10.539114,11.031080,10.530592,8.301346,9.754937,9.090264,...,7.798178,5.333055,10.050284,7.692136,10.738751,7.131421,8.104114,12.501672,9.692136,4.979418
HC17,11.509002,8.591703,10.285895,11.504704,11.327047,12.037315,11.348790,8.875303,9.376497,8.914711,...,7.670558,5.816409,11.240091,7.825628,10.506855,7.272474,7.778935,12.312777,10.012806,5.054569
HC18,11.460796,8.327901,10.018573,11.446296,11.260357,11.458320,10.870051,8.644758,9.306042,9.398463,...,8.079974,5.272619,10.654883,7.968427,10.016331,6.973059,7.753746,12.062696,10.103398,5.009584
LC05,11.453584,9.435978,10.885534,11.884092,11.422134,11.658089,11.808192,9.886975,8.696385,8.828201,...,7.569360,5.825199,11.893798,7.895588,11.472417,7.554933,7.016340,12.937899,9.490061,7.854946
LC06,10.842700,8.131066,9.787287,11.309084,10.785838,11.320140,10.804565,9.236676,9.611920,9.412247,...,8.112687,6.286717,10.022042,7.722103,10.660175,6.412247,7.366444,12.250401,10.582172,7.075212
LC07,10.955799,8.675926,9.749727,11.886886,11.102376,11.309222,10.970496,9.699642,9.106817,9.764795,...,8.738322,5.983435,10.581221,7.848505,11.093452,8.034061,7.790790,13.421038,10.037167,6.263543
LC08,11.453543,8.443634,10.179514,11.605905,10.675294,11.292735,10.872167,8.965780,9.430923,9.641017,...,7.679906,5.326951,10.289218,8.027390,10.502961,7.060777,7.963260,12.609737,9.779237,4.932672
LC09,10.430868,8.497982,9.935791,11.798771,10.536801,10.536801,10.793438,9.659137,8.782712,9.945441,...,8.444543,5.886547,10.263517,8.108940,11.484807,7.574603,7.360479,13.515094,9.670819,4.716622
LC10,11.302940,8.569007,9.852996,11.654525,11.174924,11.319400,10.887627,9.094004,9.303768,9.128041,...,8.035429,5.961848,10.166761,7.569007,10.553784,7.027437,7.919288,12.454447,9.811708,8.019399
LC11,10.991844,8.097633,9.694568,11.470498,10.593488,10.809128,10.364419,8.825553,9.257504,9.670522,...,7.820099,5.201969,10.527249,8.386729,11.090288,7.345560,8.065723,12.606814,9.993662,3.863167
LC12,11.221252,8.658457,9.959360,11.754202,10.964955,11.254631,10.929781,9.208205,8.979157,9.573103,...,8.887849,5.336529,10.125126,8.048727,10.967435,7.694830,7.509861,13.147032,9.860091,4.366903
LC13,11.001325,8.899155,9.992628,11.856051,11.206583,11.275875,10.964549,9.200459,8.875696,9.635655,...,8.423930,5.851849,10.569937,7.699846,11.291029,7.364497,7.547843,13.369020,9.734166,5.889817
LC14,11.110840,8.567126,9.912901,11.505264,11.070874,11.257192,10.927435,9.586444,9.278405,9.245640,...,8.441595,6.595140,10.189321,7.807590,10.099272,6.992732,7.708482,12.584698,10.256644,5.142628
LC15,10.687114,9.049684,10.092267,11.981914,10.695173,11.120971,11.028709,9.563785,8.881526,9.802591,...,7.683067,5.975518,10.796516,8.229701,11.575021,6.799790,7.603938,13.056543,9.263971,6.294796
LC01,11.504676,8.228577,9.850649,11.289491,11.437715,11.753998,10.927520,9.476300,9.453190,8.566746,...,8.407547,5.693302,10.726725,7.629940,8.015230,7.185155,8.072680,12.190405,10.308931,6.379802
LC02,11.119962,9.058242,10.456385,11.642025,11.074650,11.573993,11.584262,9.695672,8.795207,9.559077,...,7.955672,6.067641,10.806479,7.555742,11.449661,7.252065,7.601754,12.583443,9.320490,8.296709
LC03,11.413046,9.011260,10.243745,11.700111,11.041848,11.575463,11.329556,9.595672,9.011260,9.318938,...,8.685204,5.713854,10.458499,7.664385,11.110795,6.792709,7.573511,13.039627,9.364825,5.560048
LC04,10.937023,9.143237,10.316659,11.967907,10.746803,11.380525,11.568003,9.661368,8.902229,10.490964,...,7.665189,6.602793,10.567493,8.460499,11.843993,7.045461,7.206235,13.212859,8.691662,7.649841
ME13,11.503523,8.644884,10.205091,11.634277,11.078046,11.526279,10.944274,8.729617,9.140792,9.069435,...,8.298200,5.379120,11.054628,7.887779,10.808432,8.611781,7.981465,12.724626,9.798659,6.365945
ME14,10.939446,9.076806,10.466240,11.968062,10.944584,10.931506,10.964175,9.433444,8.891137,9.544850,...,8.481004,6.108139,10.420454,7.689339,11.441574,7.879628,7.677994,12.858218,9.634638,7.474461
ME01,10.900982,8.870436,10.127686,11.914191,10.989615,10.968314,10.822591,9.321905,8.822980,9.488155,...,7.830740,6.075079,10.749552,7.997221,11.318322,7.405346,7.691068,13.431929,9.301945,8.328498
ME02,10.959605,8.875651,10.209958,11.904341,10.937443,11.000858,11.000561,9.293276,9.034888,9.313495,...,6.754117,6.030242,11.073225,8.071530,11.629291,7.498951,7.705402,12.667848,9.301012,8.062457
ME03,10.579503,8.252588,9.870480,11.644013,10.567002,10.497554,10.265025,8.644013,9.066174,9.128759,...,8.094325,6.466928,10.062617,7.570764,11.605410,7.400839,7.908633,13.002145,10.485647,5.355035
ME04,10.300753,8.748543,9.797493,11.409205,10.489147,10.962584,10.819048,9.555204,8.991605,9.835720,...,8.042019,7.275691,9.419920,7.600313,10.995703,7.065605,6.791612,12.853755,10.582711,4.057786
ME05,10.230962,8.888319,9.871684,11.701116,10.138788,10.398432,10.543630,9.397538,9.067543,9.741114,...,7.295702,6.969932,9.816593,7.895932,12.128592,6.509298,6.611478,13.110984,10.480894,4.828576
ME06,11.303280,8.009872,9.786200,11.341589,10.945532,11.076602,10.529960,8.298262,9.022098,8.257476,...,7.633201,5.040245,11.233360,7.777211,10.074402,7.625208,7.894906,12.453027,10.286907,3.833795
ME07,11.132476,8.810548,9.939543,11.741451,11.084784,11.392565,11.021909,9.335425,9.014811,10.316901,...,8.445093,5.673045,9.861348,8.604873,11.024629,6.990527,7.845434,12.938245,9.777381,5.860130
ME08,10.951615,8.872287,10.098909,11.916456,10.999917,11.302168,11.006011,9.556093,9.248630,10.153615,...,7.834734,5.727350,10.245199,7.965581,11.087140,6.258874,8.041388,13.268764,9.584427,5.753346
ME09,11.158229,8.881389,10.210697,11.729900,11.214372,11.495042,11.128148,9.385194,9.192922,9.866516,...,7.896111,5.917915,11.004529,8.262743,11.394297,6.917915,7.789759,12.659921,9.860899,6.700323
ME10,10.636457,9.526103,10.648722,12.101616,10.779270,11.155258,11.526519,9.765960,8.993371,10.287133,...,7.836014,6.139591,10.709264,8.223984,11.689364,6.786920,7.264398,13.111481,8.941971,7.104402
ME11,11.525628,8.928954,10.673442,11.690046,11.531648,11.876306,11.793881,10.018562,8.524421,8.957857,...,8.491853,5.761460,11.349152,7.671262,10.775058,7.248447,7.176497,13.114206,9.429593,8.176497
ME12,11.211405,8.044425,9.655619,11.269651,10.800456,11.271536,10.900731,8.685631,9.479180,8.162953,...,7.981297,5.799802,10.057600,7.425988,9.784035,6.810219,7.432745,12.477343,10.328808,4.691278

In [11]:
cosine_distances = pdist(df, metric='cosine')
cosine_distances
cosine_distance_matrix = squareform(cosine_distances)
df = pd.DataFrame(cosine_distance_matrix)
df

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,0.000000,0.000490,0.000450,0.000615,0.001979,0.008406,0.001497,0.001959,0.002655,0.000751,...,0.001189,0.002928,0.002821,0.002304,0.000849,0.000971,0.000741,0.002869,0.002581,0.001837
1,0.000490,0.000000,0.000352,0.000561,0.001677,0.008443,0.001364,0.002122,0.002085,0.000594,...,0.000908,0.002230,0.002126,0.002357,0.000564,0.000871,0.000454,0.002119,0.002095,0.001954
2,0.000450,0.000352,0.000000,0.000496,0.001485,0.008061,0.001182,0.002138,0.001994,0.000716,...,0.000774,0.002233,0.002089,0.002516,0.000573,0.001159,0.000786,0.002577,0.002852,0.002262
3,0.000615,0.000561,0.000496,0.000000,0.001655,0.008111,0.001315,0.002569,0.002350,0.000622,...,0.001170,0.002723,0.002600,0.003133,0.000683,0.000734,0.000689,0.002168,0.002394,0.002672
4,0.001979,0.001677,0.001485,0.001655,0.000000,0.007556,0.000828,0.005067,0.000535,0.001508,...,0.001405,0.002428,0.001201,0.005676,0.001733,0.001999,0.001782,0.002245,0.004602,0.005645
5,0.008406,0.008443,0.008061,0.008111,0.007556,0.000000,0.007558,0.011080,0.008452,0.008368,...,0.008434,0.010176,0.009028,0.012179,0.008901,0.008957,0.008806,0.010033,0.011468,0.011813
6,0.001497,0.001364,0.001182,0.001315,0.000828,0.007558,0.000000,0.002951,0.000875,0.001335,...,0.001085,0.002789,0.002278,0.003836,0.001413,0.002103,0.001742,0.003369,0.004567,0.004324
7,0.001959,0.002122,0.002138,0.002569,0.005067,0.011080,0.002951,0.000000,0.005381,0.002865,...,0.002658,0.005241,0.006347,0.000621,0.002855,0.003717,0.002883,0.006902,0.004338,0.001067
8,0.002655,0.002085,0.001994,0.002350,0.000535,0.008452,0.000875,0.005381,0.000000,0.001969,...,0.001633,0.002721,0.001517,0.006227,0.001934,0.002643,0.002267,0.002465,0.004896,0.006539
9,0.000751,0.000594,0.000716,0.000622,0.001508,0.008368,0.001335,0.002865,0.001969,0.000000,...,0.001480,0.002966,0.002392,0.003359,0.000599,0.000499,0.000452,0.001553,0.001957,0.003082
10,0.001137,0.000911,0.001280,0.001339,0.003100,0.010119,0.002596,0.002460,0.003556,0.001173,...,0.001923,0.003005,0.003134,0.002415,0.001350,0.001493,0.000855,0.002633,0.001180,0.002083
11,0.001824,0.001280,0.001769,0.001266,0.001887,0.009754,0.002537,0.005099,0.002220,0.001200,...,0.002041,0.003200,0.002450,0.005715,0.001223,0.000912,0.000959,0.000916,0.002083,0.004744
12,0.001212,0.000817,0.001039,0.000756,0.001012,0.008582,0.001384,0.004237,0.001479,0.000622,...,0.001410,0.002300,0.001576,0.004663,0.000633,0.000652,0.000697,0.000917,0.002340,0.004292
13,0.002260,0.001768,0.002066,0.001574,0.001621,0.009103,0.002727,0.006578,0.002092,0.001415,...,0.002534,0.003189,0.002070,0.007223,0.001441,0.001038,0.001416,0.000756,0.002679,0.006239
14,0.000978,0.000638,0.000760,0.000611,0.001503,0.008727,0.001801,0.003758,0.002131,0.000542,...,0.001615,0.002473,0.001956,0.004135,0.000543,0.000486,0.000628,0.001173,0.002167,0.003530
15,0.000810,0.000954,0.000848,0.001237,0.002621,0.008509,0.001384,0.000971,0.003041,0.001479,...,0.001358,0.003908,0.003966,0.001328,0.001568,0.002101,0.001496,0.004519,0.003720,0.001525
16,0.001032,0.001062,0.001267,0.001447,0.003622,0.009967,0.002757,0.001497,0.004322,0.001363,...,0.002422,0.004341,0.004361,0.001415,0.001659,0.001717,0.001159,0.003765,0.001951,0.001329
17,0.001293,0.001470,0.001623,0.001847,0.004945,0.010929,0.003366,0.000748,0.005635,0.002122,...,0.002606,0.005092,0.005759,0.000784,0.002116,0.002518,0.001981,0.005430,0.003107,0.000655
18,0.002565,0.001857,0.002444,0.002077,0.003444,0.010370,0.003940,0.005417,0.003605,0.001800,...,0.002796,0.003905,0.003232,0.005528,0.001964,0.001851,0.001345,0.001070,0.001038,0.004693
19,0.000696,0.000631,0.000661,0.001218,0.002442,0.008703,0.001901,0.001950,0.002959,0.001245,...,0.001277,0.002902,0.002943,0.002323,0.001209,0.001725,0.001034,0.003347,0.002689,0.001615
20,0.000857,0.000663,0.001131,0.000877,0.002478,0.009034,0.002160,0.002432,0.002974,0.000872,...,0.001657,0.003039,0.003080,0.002715,0.001053,0.000895,0.000647,0.002445,0.001531,0.002259
21,0.000657,0.000574,0.000831,0.000954,0.002907,0.009447,0.002102,0.001286,0.003549,0.000995,...,0.001620,0.003688,0.003788,0.001468,0.001176,0.001219,0.000796,0.003185,0.002292,0.001056
22,0.001412,0.001018,0.001274,0.001081,0.001294,0.008671,0.001537,0.004258,0.001574,0.000930,...,0.001273,0.002193,0.001569,0.004579,0.001086,0.001168,0.001053,0.001546,0.002666,0.004437
23,0.000821,0.000595,0.000774,0.001104,0.002449,0.008847,0.002028,0.002081,0.002826,0.001119,...,0.001239,0.003058,0.003030,0.002428,0.000979,0.001535,0.000742,0.002900,0.001957,0.001882
24,0.001064,0.000914,0.000980,0.001293,0.002431,0.009160,0.001305,0.001142,0.002856,0.001418,...,0.001256,0.003190,0.003320,0.001154,0.001443,0.002134,0.001327,0.004287,0.003691,0.001673
25,0.000823,0.000618,0.000795,0.000784,0.002487,0.009644,0.001791,0.001988,0.002836,0.000953,...,0.001225,0.002340,0.002810,0.002318,0.000518,0.001270,0.000890,0.002644,0.002134,0.002192
26,0.000932,0.000436,0.000675,0.000808,0.001685,0.009143,0.001472,0.002625,0.001846,0.000817,...,0.000975,0.001778,0.001876,0.002971,0.000437,0.001128,0.000705,0.001873,0.001997,0.002780
27,0.000607,0.000726,0.000880,0.000839,0.002860,0.009787,0.002217,0.001890,0.003523,0.001037,...,0.001502,0.002589,0.003141,0.002132,0.000911,0.001216,0.001000,0.003084,0.001891,0.001665
28,0.001300,0.000723,0.001015,0.000966,0.001161,0.008929,0.001656,0.004304,0.001410,0.000682,...,0.001507,0.002029,0.001340,0.004554,0.000670,0.000811,0.000620,0.000914,0.002025,0.004081
29,0.003013,0.003427,0.003789,0.004002,0.007598,0.013619,0.005604,0.001532,0.008253,0.003978,...,0.004809,0.006786,0.008129,0.001467,0.004210,0.004705,0.003755,0.007992,0.003835,0.001354
30,0.001674,0.001264,0.001746,0.001480,0.002334,0.009622,0.002794,0.004757,0.002552,0.001016,...,0.002351,0.003574,0.002758,0.005233,0.001207,0.001047,0.000725,0.000946,0.001152,0.004393
31,0.000864,0.000660,0.000930,0.000807,0.002598,0.009508,0.002314,0.002496,0.003031,0.000706,...,0.001707,0.002892,0.002918,0.002775,0.000805,0.000883,0.000545,0.001783,0.000872,0.002183
32,0.002834,0.001995,0.002423,0.002171,0.002193,0.009567,0.003258,0.006804,0.002383,0.001576,...,0.003033,0.003238,0.002185,0.007313,0.001638,0.001519,0.001469,0.000608,0.001956,0.006400
33,0.001247,0.000930,0.001280,0.001616,0.004026,0.010828,0.003035,0.001426,0.004333,0.001663,...,0.002044,0.004463,0.004691,0.001405,0.001621,0.001965,0.001241,0.003841,0.002409,0.001103
34,0.001418,0.000776,0.001178,0.001154,0.002039,0.009610,0.002163,0.003700,0.002063,0.001080,...,0.001126,0.002479,0.002171,0.004082,0.000970,0.001352,0.000783,0.001272,0.001793,0.003433
35,0.001291,0.000686,0.001026,0.001048,0.001745,0.008777,0.001920,0.003554,0.001884,0.000797,...,0.001272,0.002985,0.002318,0.004072,0.000908,0.000965,0.000530,0.001355,0.001758,0.003431
36,0.001665,0.001004,0.001460,0.001436,0.002174,0.008697,0.002558,0.004087,0.002528,0.001333,...,0.001826,0.003870,0.002782,0.004252,0.001519,0.001303,0.000769,0.001543,0.002137,0.003528
37,0.001189,0.000908,0.000774,0.001170,0.001405,0.008434,0.001085,0.002658,0.001633,0.001480,...,0.000000,0.001972,0.001860,0.003014,0.001153,0.002113,0.001449,0.003045,0.003591,0.003171
38,0.002928,0.002230,0.002233,0.002723,0.002428,0.010176,0.002789,0.005241,0.002721,0.002966,...,0.001972,0.000000,0.000995,0.005431,0.002151,0.003752,0.003101,0.003538,0.004540,0.005396
39,0.002821,0.002126,0.002089,0.002600,0.001201,0.009028,0.002278,0.006347,0.001517,0.002392,...,0.001860,0.000995,0.000000,0.006324,0.002098,0.003022,0.002488,0.002287,0.004503,0.006264
40,0.002304,0.002357,0.002516,0.003133,0.005676,0.012179,0.003836,0.000621,0.006227,0.003359,...,0.003014,0.005431,0.006324,0.000000,0.003416,0.004159,0.003070,0.007292,0.004489,0.000771
41,0.000849,0.000564,0.000573,0.000683,0.001733,0.008901,0.001413,0.002855,0.001934,0.000599,...,0.001153,0.002151,0.002098,0.003416,0.000000,0.000848,0.000758,0.001775,0.002266,0.003216
42,0.000971,0.000871,0.001159,0.000734,0.001999,0.008957,0.002103,0.003717,0.002643,0.000499,...,0.002113,0.003752,0.003022,0.004159,0.000848,0.000000,0.000588,0.001432,0.001904,0.003441
43,0.000741,0.000454,0.000786,0.000689,0.001782,0.008806,0.001742,0.002883,0.002267,0.000452,...,0.001449,0.003101,0.002488,0.003070,0.000758,0.000588,0.000000,0.001489,0.001547,0.002573
44,0.002869,0.002119,0.002577,0.002168,0.002245,0.010033,0.003369,0.006902,0.002465,0.001553,...,0.003045,0.003538,0.002287,0.007292,0.001775,0.001432,0.001489,0.000000,0.002255,0.006427
45,0.002581,0.002095,0.002852,0.002394,0.004602,0.011468,0.004567,0.004338,0.004896,0.001957,...,0.003591,0.004540,0.004503,0.004489,0.002266,0.001904,0.001547,0.002255,0.000000,0.003618
46,0.001837,0.001954,0.002262,0.002672,0.005645,0.011813,0.004324,0.001067,0.006539,0.003082,...,0.003171,0.005396,0.006264,0.000771,0.003216,0.003441,0.002573,0.006427,0.003618,0.000000

In [12]:
similarities = df.to_numpy()
similarities
euc_observations = squareform(similarities)
euc_observations

array([0.00048989, 0.00045022, 0.00061549, ..., 0.002255  , 0.00642744,
       0.00361794])

In [13]:
network_observations, sweep_observations = sd.stad(euc_observations)

In [14]:
adjacency_matrix = network_observations.toarray()
adjacency_matrix

array([[0.        , 0.03597247, 0.03305916, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02584983, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
# collection 'bioMOBS_test_samples' looks like this: you need to run this to match the keys
# [{
#     "_key": "IAM01_1",
#     "_id": "bioMOBS_test_samples/IAM01_1",
#     "_rev": "_dimFSyO---",
#     "individual": "IAM01",
#     "age": 58,
#     "gender": "M",
#     "X__Saturatie": -1.090955188,
#     "Albumine": -0.688442937,
#     "Albumine____": 0.706384552,
#     "Aldosteron": 1.598158214,
#     "Alfa_1_globulinen": -1.139896645,
#     "Alfa_2_globulinen": 0.34075838,
#     ...

aql = "FOR x IN BBS3004_samples RETURN x"
queryResult = db.AQLQuery(aql, rawResults=True, batchSize=100)
data = pd.DataFrame(queryResult)
data

,_key,_id,_rev,CD96,ACSL4,DLD,GRB2,AKT3,GLS,ROCK1,...,SESN3,MX2,CD14,GADD45A,GOT2,HLA.DPB1,PVRIG,IL1R2,phenotype,individual
0,HC01,MSP_samples/HC01,_jxVgt4a---,10.9824,8.5819,9.8084,11.4862,10.6408,11.1295,10.6454,...,9.7454,7.8288,10.9897,6.6385,7.8125,12.4252,10.1311,5.4405,control,HC01
1,HC02,MSP_samples/HC02,_jxVgt4a--_,11.0744,8.5767,9.8126,11.7324,11.0194,11.1875,10.8069,...,10.4558,7.9049,11.0775,7.3469,7.6081,12.5105,9.7598,5.6551,control,HC02
2,HC03,MSP_samples/HC03,_jxVgt4a--A,10.9145,8.6557,9.8228,11.4940,10.9185,11.0220,10.7156,...,10.2407,7.6813,11.1521,6.5763,7.5488,12.8835,9.9036,5.0183,control,HC03
3,HC04,MSP_samples/HC04,_jxVgt4e---,10.7834,8.7936,9.9468,11.6330,10.6905,11.1692,10.7904,...,10.2163,7.6703,11.2152,6.2931,7.9690,13.4574,9.6533,4.5794,control,HC04
4,HC05,MSP_samples/HC05,_jxVgt4e--_,9.9351,8.8969,9.7030,11.8124,9.7399,10.3481,10.4194,...,9.3391,7.6960,12.3244,5.9211,7.7602,13.6501,9.8043,5.1841,control,HC05
5,HC06,MSP_samples/HC06,_jxVgt4e--A,11.1123,6.5577,10.1724,12.9933,11.3325,11.5407,11.0089,...,9.6870,9.0334,11.6714,4.8796,5.3650,13.4817,10.3521,4.5577,control,HC06
6,HC07,MSP_samples/HC07,_jxVgt4e--B,10.4482,8.4806,9.8782,11.8324,10.6312,10.7438,10.1212,...,9.5030,7.9700,11.6689,6.5217,7.7914,13.2736,9.5284,4.5876,control,HC07
7,HC08,MSP_samples/HC08,_jxVgt4e--C,11.3590,8.0662,9.8172,11.6228,11.0503,11.1425,10.3825,...,10.3825,7.5466,9.4901,7.1941,8.0161,12.7796,9.8359,4.5567,control,HC08
8,HC09,MSP_samples/HC09,_jxVgt4e--D,10.3830,9.0202,9.8926,12.0776,10.1853,10.3292,10.2719,...,9.5950,7.8358,12.5528,6.8888,7.7808,13.8988,9.4886,6.6812,control,HC09
9,HC10,MSP_samples/HC10,_jxVgt4e--E,11.1877,8.8253,10.1040,11.8363,11.1464,11.5205,11.0865,...,10.7212,8.5273,10.7877,6.4460,8.1704,13.4515,9.5996,5.6229,control,HC10
10,HC11,MSP_samples/HC11,_jxVgt4e--F,11.6416,8.6971,10.4170,11.5526,11.3046,11.8016,11.5839,...,11.0980,7.8003,11.1440,7.4869,7.2955,12.7384,10.1548,4.8934,control,HC11
11,HC12,MSP_samples/HC12,_jxVgt4e--G,10.4825,9.1143,10.3388,12.0408,10.6186,10.9107,10.9696,...,10.5723,8.1294,11.3725,7.4148,7.5331,13.6771,9.6078,7.0680,control,HC12
12,HC13,MSP_samples/HC13,_jxVgt4e--H,10.8065,9.0815,10.2057,11.9961,10.4095,11.1171,10.9424,...,9.9986,8.1443,11.8136,7.1674,7.7432,13.2655,9.4182,5.3554,control,HC13
13,HC14,MSP_samples/HC14,_jxVgt4e--I,10.4889,9.2429,10.1524,12.1310,10.3698,10.9856,11.1208,...,10.2039,8.0459,11.7491,6.8618,7.6895,13.4162,9.2414,7.5605,control,HC14
14,HC15,MSP_samples/HC15,_jxVgt4e--J,11.0625,8.9579,10.0315,11.8193,10.5671,11.1700,10.8831,...,10.5400,8.1090,11.0547,6.1610,7.8580,12.4887,9.6124,4.6191,control,HC15
15,HC16,MSP_samples/HC16,_jxVgt4e--K,11.1133,8.4960,9.7637,11.6257,10.5391,11.0311,10.5306,...,10.0503,7.6921,10.7388,7.1314,8.1041,12.5017,9.6921,4.9794,control,HC16
16,HC17,MSP_samples/HC17,_jxVgt4e--L,11.5090,8.5917,10.2859,11.5047,11.3270,12.0373,11.3488,...,11.2401,7.8256,10.5069,7.2725,7.7789,12.3128,10.0128,5.0546,control,HC17
17,HC18,MSP_samples/HC18,_jxVgt4e--M,11.4608,8.3279,10.0186,11.4463,11.2604,11.4583,10.8701,...,10.6549,7.9684,10.0163,6.9731,7.7537,12.0627,10.1034,5.0096,control,HC18
18,LC05,MSP_samples/LC05,_jxVgt4e--N,11.4536,9.4360,10.8855,11.8841,11.4221,11.6581,11.8082,...,11.8938,7.8956,11.4724,7.5549,7.0163,12.9379,9.4901,7.8549,post_covid,LC05
19,LC06,MSP_samples/LC06,_jxVgt4e--O,10.8427,8.1311,9.7873,11.3091,10.7858,11.3201,10.8046,...,10.0220,7.7221,10.6602,6.4122,7.3664,12.2504,10.5822,7.0752,post_covid,LC06
20,LC07,MSP_samples/LC07,_jxVgt4e--P,10.9558,8.6759,9.7497,11.8869,11.1024,11.3092,10.9705,...,10.5812,7.8485,11.0935,8.0341,7.7908,13.4210,10.0372,6.2635,post_covid,LC07
21,LC08,MSP_samples/LC08,_jxVgt4e--Q,11.4535,8.4436,10.1795,11.6059,10.6753,11.2927,10.8722,...,10.2892,8.0274,10.5030,7.0608,7.9633,12.6097,9.7792,4.9327,post_covid,LC08
22,LC09,MSP_samples/LC09,_jxVgt4e--R,10.4309,8.4980,9.9358,11.7988,10.5368,10.5368,10.7934,...,10.2635,8.1089,11.4848,7.5746,7.3605,13.5151,9.6708,4.7166,post_covid,LC09
23,LC10,MSP_samples/LC10,_jxVgt4e--S,11.3029,8.5690,9.8530,11.6545,11.1749,11.3194,10.8876,...,10.1668,7.5690,10.5538,7.0274,7.9193,12.4544,9.8117,8.0194,post_covid,LC10
24,LC11,MSP_samples/LC11,_jxVgt4e--T,10.9918,8.0976,9.6946,11.4705,10.5935,10.8091,10.3644,...,10.5272,8.3867,11.0903,7.3456,8.0657,12.6068,9.9937,3.8632,post_covid,LC11
25,LC12,MSP_samples/LC12,_jxVgt4e--U,11.2213,8.6585,9.9594,11.7542,10.9650,11.2546,10.9298,...,10.1251,8.0487,10.9674,7.6948,7.5099,13.1470,9.8601,4.3669,post_covid,LC12
26,LC13,MSP_samples/LC13,_jxVgt4e--V,11.0013,8.8992,9.9926,11.8561,11.2066,11.2759,10.9645,...,10.5699,7.6998,11.2910,7.3645,7.5478,13.3690,9.7342,5.8898,post_covid,LC13
27,LC14,MSP_samples/LC14,_jxVgt4e--W,11.1108,8.5671,9.9129,11.5053,11.0709,11.2572,10.9274,...,10.1893,7.8076,10.0993,6.9927,7.7085,12.5847,10.2566,5.1426,post_covid,LC14
28,LC15,MSP_samples/LC15,_jxVgt4e--X,10.6871,9.0497,10.0923,11.9819,10.6952,11.1210,11.0287,...,10.7965,8.2297,11.5750,6.7998,7.6039,13.0565,9.2640,6.2948,post_covid,LC15
29,LC01,MSP_samples/LC01,_jxVgt4e--Y,11.5047,8.2286,9.8506,11.2895,11.4377,11.7540,10.9275,...,10.7267,7.6299,8.0152,7.1852,8.0727,12.1904,10.3089,6.3798,post_covid,LC01
30,LC02,MSP_samples/LC02,_jxVgt4e--Z,11.1200,9.0582,10.4564,11.6420,11.0747,11.5740,11.5843,...,10.8065,7.5557,11.4497,7.2521,7.6018,12.5834,9.3205,8.2967,post_covid,LC02
31,LC03,MSP_samples/LC03,_jxVgt4e--a,11.4130,9.0113,10.2437,11.7001,11.0418,11.5755,11.3296,...,10.4585,7.6644,11.1108,6.7927,7.5735,13.0396,9.3648,5.5600,post_covid,LC03
32,LC04,MSP_samples/LC04,_jxVgt4i---,10.9370,9.1432,10.3167,11.9679,10.7468,11.3805,11.5680,...,10.5675,8.4605,11.8440,7.0455,7.2062,13.2129,8.6917,7.6498,post_covid,LC04
33,ME13,MSP_samples/ME13,_jxVgt4i--_,11.5035,8.6449,10.2051,11.6343,11.0780,11.5263,10.9443,...,11.0546,7.8878,10.8084,8.6118,7.9815,12.7246,9.7987,6.3659,CFS,ME13
34,ME14,MSP_samples/ME14,_jxVgt4i--A,10.9394,9.0768,10.4662,11.9681,10.9446,10.9315,10.9642,...,10.4205,7.6893,11.4416,7.8796,7.6780,12.8582,9.6346,7.4745,CFS,ME14
35,ME01,MSP_samples/ME01,_jxVgt4i--B,10.9010,8.8704,10.1277,11.9142,10.9896,10.9683,10.8226,...,10.7496,7.9972,11.3183,7.4053,7.6911,13.4319,9.3019,8.3285,CFS,ME01
36,ME02,MSP_samples/ME02,_jxVgt4i--C,10.9596,8.8757,10.2100,11.9043,10.9374,11.0009,11.0006,...,11.0732,8.0715,11.6293,7.4990,7.7054,12.6678,9.3010,8.0625,CFS,ME02
37,ME03,MSP_samples/ME03,_jxVgt4i--D,10.5795,8.2526,9.8705,11.6440,10.5670,10.4976,10.2650,...,10.0626,7.5708,11.6054,7.4008,7.9086,13.0021,10.4856,5.3550,CFS,ME03
38,ME04,MSP_samples/ME04,_jxVgt4i--E,10.3008,8.7485,9.7975,11.4092,10.4891,10.9626,10.8190,...,9.4199,7.6003,10.9957,7.0656,6.7916,12.8538,10.5827,4.0578,CFS,ME04
39,ME05,MSP_samples/ME05,_jxVgt4i--F,10.2310,8.8883,9.8717,11.7011,10.1388,10.3984,10.5436,...,9.8166,7.8959,12.1286,6.5093,6.6115,13.1110,10.4809,4.8286,CFS,ME05
40,ME06,MSP_samples/ME06,_jxVgt4i--G,11.3033,8.0099,9.7862,11.3416,10.9455,11.0766,10.5300,...,11.2334,7.7772,10.0744,7.6252,7.8949,12.4530,10.2869,3.8338,CFS,ME06
41,ME07,MSP_samples/ME07,_jxVgt4i--H,11.1325,8.8105,9.9395,11.7415,11.0848,11.3926,11.0219,...,9.8613,8.6049,11.0246,6.9905,7.8454,12.9382,9.7774,5.8601,CFS,ME07
42,ME08,MSP_samples/ME08,_jxVgt4i--I,10.9516,8.8723,10.0989,11.9165,10.9999,11.3022,11.0060,...,10.2452,7.9656,11.0871,6.2589,8.0414,13.2688,9.5844,5.7533,CFS,ME08
43,ME09,MSP_samples/ME09,_jxVgt4i--J,11.1582,8.8814,10.2107,11.7299,11.2144,11.4950,11.1281,...,11.0045,8.2627,11.3943,6.9179,7.7898,12.6599,9.8609,6.7003,CFS,ME09
44,ME10,MSP_samples/ME10,_jxVgt4i--K,10.6365,9.5261,10.6487,12.1016,10.7793,11.1553,11.5265,...,10.7093,8.2240,11.6894,6.7869,7.2644,13.1115,8.9420,7.1044,CFS,ME10
45,ME11,MSP_samples/ME11,_jxVgt4i--L,11.5256,8.9290,10.6734,11.6900,11.5316,11.8763,11.7939,...,11.3492,7.6713,10.7751,7.2484,7.1765,13.1142,9.4296,8.1765,CFS,ME11
46,ME12,MSP_samples/ME12,_jxVgt4i--M,11.2114,8.0444,9.6556,11.2697,10.8005,11.2715,10.9007,...,10.0576,7.4260,9.7840,6.8102,7.4327,12.4773,10.3288,4.6913,CFS,ME12

In [ ]:
#Before running this box make sure you create empty EDGE type named BBS3004_edges (or any other name as log is the name matches with the what you type here) so that you can populate that file by running this script. 
edgesCollection = db["BBS3004_edges"]
edgesCollection.truncate()
docs = []
for i in range(len(np.nonzero(adjacency_matrix)[0])):
    x = np.nonzero(adjacency_matrix)[0][i]
    y = np.nonzero(adjacency_matrix)[1][i]
    x_key = data.iloc[x]["_key"]
    y_key = data.iloc[y]["_key"]

    doc = edgesCollection.createDocument()
    doc['_key'] = x_key + '_' + y_key
    doc['_from'] = "BBS3004_samples/" + x_key
    doc['_to'] = "BBS3004_samples/" + y_key
    doc["weight"] = adjacency_matrix[x][y]
    docs.append(doc)

In [ ]:
#The crucial part of code do not forget this cell to put it actually in arangODB
edgesCollection.bulkSave(docs)

### proces the sample file properly first so that it's ok for putting into arangodb :

In [ ]:
# For modifying the JSON file, upload the modified_file.json into arandob and make sure the connection to that file is defined properly in the obsolete files that annotation inside the interactive stad analyses portal is possible. 
with open("BBS3004_samples.json", "r") as f:
    data = json.load(f)

keys = [
    "HC01", "HC02", "HC03", "HC04", "HC05", "HC06", "HC07", "HC08", "HC09", "HC10", "HC11", "HC12", "HC13", "HC14", "HC15", "HC16", "HC17", "HC18",
  "LC05", "LC06", "LC07", "LC08", "LC09", "LC10", "LC11", "LC12", "LC13", "LC14", "LC15", "LC01", "LC02", "LC03", "LC04",
  "ME13", "ME14", "ME01", "ME02", "ME03", "ME04", "ME05", "ME06", "ME07", "ME08", "ME09", "ME10", "ME11", "ME12"
]


# Modify data

for i, item in enumerate(data):
    # Assign profile
    item["phenotype"] = "control" if i < 18 else "post_covid"
    
    
    # Assign duration
    if i < 18:
        item["phenotype"] = "control"
    elif i < 33:
        item["phenotype"] = "post_covid"
    else:
        item["phenotype"] = "CFS"
    
    # Add _key and individual if keys exist
    if i < len(keys):
        item["_key"] = keys[i]
        item["individual"] = keys[i]

# Save modified JSON file
with open("modified_file.json", "w") as f:
    json.dump(data, f, indent=4)

print("JSON file has been updated and saved as modified_file.json")

In [ ]:
#Final test to check whether your data upload was succsefull. Adjust the BBS3004_samples' file name into your arangoDB file. so that you can have a look at , so this needs to come later
aql = "FOR x IN BBS3004_samples RETURN x"
queryResult = db.AQLQuery(aql, rawResults=True, batchSize=100)
data = pd.DataFrame(queryResult)
data